-- MySQL Script generated by MySQL Workbench
-- Sun Aug  4 19:20:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hometask` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hometask` DEFAULT CHARACTER SET utf8 ;
USE `hometask` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `clnt_id` INT NOT NULL,
  `clnt_name` VARCHAR(50) NOT NULL,
  `clnt_surname` VARCHAR(50) NOT NULL,
  `clnt_phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`clnt_id`),
  UNIQUE INDEX `clientphone_UNIQUE` (`clnt_phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rates` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rates` (
  `rate_id` INT NOT NULL AUTO_INCREMENT,
  `rate_type` VARCHAR(255) NOT NULL,
  `rate_cost` DECIMAL(18,2) NOT NULL,
  `dlvr_days` INT NOT NULL,
  PRIMARY KEY (`rate_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `clnt_id` INT NOT NULL,
  `rate_id` INT NOT NULL,
  `dlvr_date` DATE NOT NULL,
  `dlvr_address` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `clnt_id_idx` (`clnt_id` ASC) VISIBLE,
  INDEX `rate_id_idx` (`rate_id` ASC) VISIBLE,
  CONSTRAINT `clnt_id`
    FOREIGN KEY (`clnt_id`)
    REFERENCES `mydb`.`Clients` (`clnt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rate_id`
    FOREIGN KEY (`rate_id`)
    REFERENCES `mydb`.`rates` (`rate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
